services:
  postgres:
    ports: []
    restart: unless-stopped

  redis:
    ports: []
    restart: unless-stopped

  app:
    env_file: .env.prod
    environment:
      NODE_ENV: production
    restart: unless-stopped

  worker:
    env_file: .env.prod
    environment:
      NODE_ENV: production
    restart: unless-stopped
